classdef RectangularElement
    properties
        Position(1,3) single = [0, 0, 0];
        Normal(1,3) single = [0, 0, 1];
        Size(1,2) single = [1, 1]*1e-4;
        Apodization(1,1) single = 1;
        Delay(1,1) single = 0;
        Active(1,1) logical = true;
    end

    methods
        function bytes = ToBytes(element)
            bytes = [ ...
                typecast(element.Position, 'uint8'), ...
                zeros(1, 4, 'uint8'), ...
                typecast(element.Normal, 'uint8'), ...
                zeros(1, 4, 'uint8'), ...
                typecast(element.Size, 'uint8'), ...
                zeros(1, 8, 'uint8'), ...
                typecast(element.Apodization, 'uint8'), ...
                typecast(element.Delay, 'uint8'), ...
                typecast(uint32(element.Active), 'uint8'), ...
                zeros(1, 4, 'uint8'), ...
                ];
        end
    end
end