classdef Settings
    %UNTITLED Summary of this class goes here
    %   Detailed explanation goes here

    properties (Constant)
        SizeOf = 32;
    end

    properties
        SamplingFrequency(1,1) single = 100e6;
        SpeedOfSound(1,1) single = 1540;
        TransmitElementCount(1,1) int32 = 0;
        ReceiveElementCount(1,1) int32 = 0;
        ScatterCount(1,1) int32 = 0;
        StartTime(1,1) single = 0;
        SampleCount(1,1) int32 = 0;
        Headless(1,1) logical = true;
    end

    methods
        function s = ToStruct(settings)
            s = struct(...
                'samplingFrequency', settings.SamplingFrequency, ...
                'speedOfSound', settings.SpeedOfSound, ...
                'transmitElementCount', settings.TransmitElementCount, ...
                'receiveElementCount', settings.ReceiveElementCount, ...
                'scatterCount', settings.ScatterCount, ...
                'startTime', settings.StartTime, ...
                'sampleCount', settings.SampleCount, ...
                'headless', settings.Headless);
        end

        function bytes = ToBytes(settings)
            bytes = zeros(1, vkField.Settings.SizeOf, 'uint8');
            bytes(1:vkField.Settings.SizeOf) = [ ...
                typecast(settings.SamplingFrequency, 'uint8'), ...
                typecast(settings.SpeedOfSound, 'uint8'), ...
                typecast(settings.TransmitElementCount, 'uint8'), ...
                typecast(settings.ReceiveElementCount, 'uint8'), ...
                typecast(settings.ScatterCount, 'uint8'), ...
                typecast(settings.StartTime, 'uint8'), ...
                typecast(settings.SampleCount, 'uint8'), ...
                typecast(settings.Headless, 'uint8'), ...
                zeros(1, 3, 'uint8'), ...
                ];
        end
    end
end